pagarme/ecommerce-module-core

src/Kernel/Services/OrderService.php
src/Kernel/ValueObjects/TransactionStatus.php
tests/Kernel/ValueObjects/TransactionStatusTest.php

| **What?**         | This PR brings changes that were implemented in the mundipagg repository.
NOTE:
PRs made in the mundipagg repository:
https://github.com/mundipagg/ecommerce-module-core/pull/215
https://github.com/mundipagg/ecommerce-module-core/pull/217
https://github.com/mundipagg/ecommerce-module-core/pull/220

Changes from mundipagg repo

---

src/Hub/Factories/HubCommandFactory.php
src/Hub/Services/HubIntegrationService.php
src/Kernel/Abstractions/AbstractModuleCoreSetup.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-145
| **What?**         | Changes Hub API URL

Changes Hub API URL

---

src/Hub/Commands/InstallCommand.php
src/Hub/Factories/HubCommandFactory.php
src/Hub/Services/HubIntegrationService.php
src/Kernel/Abstractions/AbstractModuleCoreSetup.php
src/Kernel/Aggregates/Configuration.php
src/Kernel/Factories/ConfigurationFactory.php
tests/Hub/Factories/HubCommandFactoryTest.php
tests/Kernel/Aggregates/ConfigurationTests.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-165
| **What?**         | Adds Hub environment info
| **Why?**          | To show the Hub's environment integrated
| **How?**          | Saving the type returned by Hub's API

[Feature] Adds Hub environment info

---

src/Kernel/Services/ChargeService.php
src/Payment/Services/ResponseHandlers/OrderHandler.php

| **Issue**           | https://mundipagg.atlassian.net/browse/PAOP-194
| **What?**         | Fixes charge capture made by a customer not registered in the website (guest)
| **How?**          | Checking if the charge have a customer object setted before using it.

Fixes charge capture for guest customer

---

src/Hub/Commands/AbstractCommand.php
src/Hub/Commands/InstallCommand.php
src/Hub/Commands/UninstallCommand.php
src/Hub/Services/HubIntegrationService.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-164
| **What?**         | Improve logs in hub integration proccess.
| **Why?**          | To clarify errors during the hub integration.
| **How?**          | Calling log service to write important info and writing exceptions.
Example of a successful integration log:
```
[2021-07-06 05:10:48] Hub.INFO: Valid install token received: 31830fd70201a6bf7ba132a09a2bc2c3e76d3f3366c3f5551b4dc21512dd2e5009341c6563f105df6a65904c8acd9fc9ab473618a41056f07149399e925932ad
Version: m: 1.1.0 c: 1.1.0 p: Magento Community 2.4.1 
From: /var/www/magento2.localhost/public_html/app/code/Pagarme/Pagarme/Controller/Adminhtml/Hub/Index.php:75 -> …
```

Improve hub integration logs

---

src/Kernel/Aggregates/Order.php
src/Kernel/I18N/ENUS.php
src/Kernel/I18N/PTBR.php
src/Kernel/Services/OrderService.php
src/Payment/Aggregates/Payments/AbstractPayment.php
src/Payment/Services/ResponseHandlers/OrderHandler.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-234
| **What?**         | Adds split on order creation
| **Why?**          | To allow payment with split
Dash
Admin

[Feature] Adds split on order creation

---

src/Kernel/Abstractions/AbstractDatabaseDecorator.php
src/Kernel/I18N/ENUS.php
src/Kernel/I18N/PTBR.php
src/Kernel/ValueObjects/Id/RecipientId.php
src/Marketplace/Aggregates/Recipient.php
src/Marketplace/Factories/RecipientFactory.php
src/Marketplace/Interfaces/RecipientInterface.php
src/Marketplace/Repositories/RecipientRepository.php
src/Marketplace/Services/RecipientService.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-252
| **What?**         | Adds recipients table and saves recipients data to database
| **How?**          | A structure was created inside the src folder following the project pattern. The root directory was called Markeplace and within the directory was created Aggregates, Factories, Interfaces, Repositories and Services

Adds recipients table

---

src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
src/Kernel/Interfaces/PlatformOrderInterface.php
src/Kernel/Services/OrderService.php
src/Marketplace/Aggregates/Recipient.php
src/Marketplace/Aggregates/Split.php
src/Marketplace/Factories/RecipientFactory.php
src/Marketplace/Interfaces/ConvertibleToSDKRequestsInterface.php
src/Marketplace/Interfaces/RecipientInterface.php
src/Marketplace/Repositories/RecipientRepository.php
src/Marketplace/Services/RecipientService.php
src/Payment/Aggregates/Order.php
src/Payment/Aggregates/Payments/AbstractPayment.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-251
| **What?**         | Integration with Webkul module
| **Why?**          | To allow payment with split

Webkul integration

---

src/Kernel/Factories/Configurations/MarketplaceConfigFactory.php
src/Kernel/ValueObjects/Configuration/MarketplaceConfig.php
src/Marketplace/Aggregates/Split.php
src/Payment/Aggregates/Payments/AbstractPayment.php
tests/Marketplace/Aggregates/SplitTest.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-273
| **What?**         | Development of split remainder logic
| **Why?**          | To allow payment with split

Adds split remainder logic

---

src/Payment/Aggregates/Payments/AbstractPayment.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-251
| **What?**         | Fixes a bug that doesn't allow us to create split orders with more than two charges
| **Why?**          | To allow marketplaces to create orders with multimeans
| **How?**          | creating split array with values relative to payment amount

Fix split with two charges or more

---

src/Marketplace/Services/RecipientService.php

| **What?**         | Fixed wrong called method
| **Why?**          | To fix the recipient update
| **How?**          | Calling the method from the correct object

:bug: Fixed incorrect method

---

src/Kernel/Aggregates/Configuration.php
src/Kernel/Factories/ConfigurationFactory.php
src/Kernel/Factories/Configurations/VoucherConfigFactory.php
src/Kernel/ValueObjects/Configuration/VoucherConfig.php
src/Payment/Aggregates/Payments/NewVoucherPayment.php
src/Payment/Factories/PaymentFactory.php

| **Issue**         | Get savedVoucherCards flag
| **What?**         | Enable wallet voucher cards
| **Why?**          | Wallet voucher cards not updating value in database?

:bug: load and save savedVoucherCards in database

---

src/Marketplace/Factories/RecipientFactory.php

Set document type recipient by document.

:sparkles: Add document type validation by document

---

src/Kernel/Factories/ConfigurationFactory.php

check the variable before adding to the object.

:bug: check saveVoucherCards variable

---

composer.json
src/Kernel/Aggregates/Configuration.php
src/Kernel/Factories/ConfigurationFactory.php
src/Kernel/Factories/Configurations/VoucherConfigFactory.php
src/Kernel/Factories/TransactionFactory.php
src/Kernel/Services/LogService.php
src/Kernel/Services/OrderCreationService.php
src/Kernel/Services/OrderService.php
src/Kernel/ValueObjects/Configuration/VoucherConfig.php
src/Payment/Aggregates/Order.php
src/Payment/Aggregates/Payments/NewVoucherPayment.php
src/Payment/Aggregates/SavedCard.php
src/Payment/Factories/PaymentFactory.php
src/Payment/Factories/SavedCardFactory.php
src/Payment/Repositories/SavedCardRepository.php
src/Payment/Services/CardService.php
src/Webhook/Services/WebhookReceiverService.php

Save Voucher Card
Hide sensitive data in log files

Voucher Card

---

src/Kernel/Log/BlurData.php
src/Kernel/Services/LogService.php
src/Webhook/Services/WebhookReceiverService.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-256
| **What?**         | Non-existent indexes when handling logs
| **Why?**          | Error
| **How?**          | Refatoring

:bug: fix log

---

src/Kernel/Services/OrderService.php
src/Payment/Factories/PaymentFactory.php

| **Issue**         | https://mundipagg.atlassian.net/jira/software/c/projects/PAOPN/boards/690?modal=detail&selectedIssue=PAOPN-94
| **What?**         | add multi-buyer on voucher payments.
| **How?**          | Send mult-buyer payment data to request data

PAOPN-94: add multi-buyer on voucher payments

---

src/Kernel/Services/LogService.php
src/Kernel/Services/OrderCreationService.php

solve sourceObject reference in log

:bug: solve sourceObject reference in log

---

src/Payment/Aggregates/Customer.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-273
| **What?**         | Error when creating/editing customer data through the administrative portal.
| **Why?**          | Editing client info through admin was causing a error
| **How?**          | Check if the customer already exists at Pagar.Me, if it already exists, perform the validation ignoring the 'document' field if it i

Bug fix editing customer through admin

---

composer.json

Update for PHP 8

---

src/Payment/Aggregates/Address.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-288
| **What?**         | Fixes problem when purchase made with multibuyer
| **Why?**          | Fixes problem when purchase made with multibuyer
| **How?**          | If country in multibuyer is null, it is fixed BR,

If the country in the multiclient is null fixed br

---

src/Kernel/ValueObjects/Configuration/MarketplaceConfig.php
src/Payment/Aggregates/Order.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-304
| **What?**         | Fix conflict bug and add php8 compatibility
| **Why?**          | Fix conflict bug and add php8 compatibility
| **How?**          | Add #[\ReturnTypeWillChange]

Fix conflict bug and add php8 compatibility to split

---

composer.json
src/Hub/Aggregates/InstallToken.php
src/Hub/Services/HubIntegrationService.php
src/Kernel/Abstractions/AbstractModuleCoreSetup.php
src/Kernel/Aggregates/Charge.php
src/Kernel/Aggregates/Configuration.php
src/Kernel/Services/OrderService.php
src/Payment/Aggregates/Payments/AbstractPayment.php
src/Webhook/Services/ChargeOrderService.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-490
| **What?**         | Compatibization with woocommerce.
| **Why?**          | Update woocommerce and magento with the latestest version of ecommerce-module-core
| **How?**          | Bringing woocommerce ecommerce-module-core changes to here

PAOPN-490: Compatibization with woocommerce

---

README.md
composer.json

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-490
| **What?**         | Updating module name and php versions.
| **Why?**          | Update composer config and documentation.
| **How?**          | Updating module name and php versions.

PAOPN-490 - Updating versions

---

src/Middle/Client.php
src/Middle/Interfaces/CardInterface.php
src/Middle/Interfaces/ConvertToLegacyInterface.php
src/Middle/Model/Card.php
src/Middle/Model/Customer.php
src/Middle/Model/Customer/Address.php
src/Middle/Model/Customer/Phones.php
src/Middle/Proxy/CardProxy.php
src/Middle/Proxy/CustomerProxy.php
src/Middle/Service/CardService.php
src/Payment/Aggregates/Payments/AbstractCreditCardPayment.php
src/Payment/Factories/PaymentFactory.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-490
| **What?**         | Compatibilization with woocommerce subscrition.
| **Why?**          | Equalize woocommerce and magento changes in ecommerce-module-core
| **How?**          | Adding card connection and recurrence cycle information

PAOPN-490: Compatibilization with woocommerce subscrition

---

src/Recurrence/Aggregates/Plan.php
src/Recurrence/Aggregates/ProductSubscription.php
src/Recurrence/Aggregates/Repetition.php
src/Recurrence/Factories/PlanFactory.php
src/Recurrence/Factories/ProductSubscriptionFactory.php
src/Recurrence/Repositories/PlanRepository.php
src/Recurrence/Repositories/ProductSubscriptionRepository.php
src/Recurrence/Services/RecurrenceService.php
src/Recurrence/Services/SubscriptionService.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-575
| **What?**         | Changing cycles to discount in subscriptions and plans.
| **Why?**          | To be able to apply discount in all charges from subscriptions and plans.
| **How?**          | Changing cycles to discount in subscriptions and plans.

feat: changing cycles to discount in subscriptions and plans

---

src/Hub/Commands/InstallCommand.php
src/Kernel/Abstractions/AbstractModuleCoreSetup.php
src/Kernel/Aggregates/Configuration.php
src/Middle/Client.php
src/Middle/Model/Account.php
src/Middle/Model/Card.php
src/Middle/Proxy/AccountProxy.php

Questions | Answers
-- | --
Issue | https://mundipagg.atlassian.net/browse/PAOPN-329
What? | Create call to API getAccount
Why? | Validation of configuration parameters in Dash Pagarme.
How? | Create middleware for account information.

feat: create call to API getAccount (middleware)

---

src/Recurrence/Services/RecurrenceService.php
src/Recurrence/Services/SubscriptionService.php

| **What?**         | zero cycle discount and removing unnecessary increment
| **Why?**          | zero cycle discount and removing unnecessary increment
| **How?**          | zero cycle discount and removing unnecessary increment

fix: zero cycle discount and removing unnecessary increment

---

composer.json

- Pagar.me Dash settings validation responsibilities
-  Log blur function receiving null in argument
- Sending billet settings to order

Release 2.3.0

---

composer.json
src/Middle/Model/Account.php

Release 2.3.1

---

src/Payment/Aggregates/Order.php
src/Payment/Aggregates/Payments/AbstractCreditCardPayment.php
src/Payment/Aggregates/Payments/Authentication/Authentication.php
src/Payment/Aggregates/Payments/Authentication/AuthenticationStatusEnum.php
src/Payment/Aggregates/Payments/Authentication/Type/ThreeDSecure.php
src/Payment/Factories/PaymentFactory.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-638
| **What?**         | Sending authentication node to 3ds order.
| **Why?**          | To create order with 3ds authentication in pagar.me
| **How?**          | Sending authentication node inside card node to createOrder request.

feat: sending authentication node to 3ds order

---

src/Payment/Aggregates/Payments/Authentication/AuthenticationStatusEnum.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-639
| **What?**         | Adding 3ds status to admin order.
| **Why?**          | Show 3ds status for orders to admin users.
| **How?**          | Adding 3ds status to admin order.

feat: 3ds status messages

---

src/Middle/Client.php
src/Middle/Proxy/TdsTokenProxy.php

| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-649
| **What?**         | Changing environment to get tds token deppending on account type.
| **Why?**          | To call the correct get td token endpoint.
| **How?**          | Changing environment to get tds token deppending on account type.

feat: changing environment to get tds token deppending on account type

---

src/Payment/Aggregates/Address.php

> [!IMPORTANT]
Alterado a validação do campo número para aceitar o valor 0.
Compra com endereço com número 123 com sucesso.
Compra com endereço com número 0 com sucesso.

fix: zero in address number field

---

src/Kernel/Services/LogService.php
src/Marketplace/Factories/RecipientFactory.php
src/Middle/Factory/RecipientFactory.php
src/Middle/Interfaces/BaseRecipientInterface.php
src/Middle/Model/Address.php
src/Middle/Model/Common/Document.php
src/Middle/Model/Marketplace/BankAccount.php
src/Middle/Model/Marketplace/BasePersonInformation.php
src/Middle/Model/Marketplace/BaseRegisterInformation.php
src/Middle/Model/Marketplace/CorporationRegisterInformation.php
src/Middle/Model/Marketplace/IndividualRegisterInformation.php
src/Middle/Model/Marketplace/ManagingPartner.php
src/Middle/Model/Marketplace/TransferSettings.php
src/Middle/Model/Phones.php
src/Middle/Model/Recipient.php
src/Middle/Proxy/RecipientProxy.php
tests/Middle/Factory/RecipientFactoryTest.php

> [!IMPORTANT]
Adicionado novas campos no cadastro de recebedores para atender a determinação do Bacen.
Cadastro de novos recebedores PF e PJ, com novas informações, e também buscando dados de recebedores já cadastrados na Dash do Pagar.me (cenário de recebedor antigo, já que a Dash ainda não recebeu essa atualização)

feat: added new fields to recipient

---

.gitignore
src/Marketplace/Aggregates/Recipient.php
src/Marketplace/Factories/RecipientFactory.php
src/Marketplace/Interfaces/RecipientInterface.php
src/Marketplace/Repositories/RecipientRepository.php
src/Marketplace/Services/RecipientService.php
src/Webhook/Aggregates/Webhook.php
src/Webhook/Services/RecipientHandlerService.php
tests/Marketplace/Aggregates/RecipientTest.php
tests/Marketplace/Factories/RecipientFactoryTest.php
tests/Webhook/Aggregates/WebhookTest.php
tests/Webhook/Services/RecipientHandlerServiceTest.php

Adição do handler dos webhooks recipient.
Teste de webhooks com os status do [épico](https://mundipagg.atlassian.net/browse/PA-933).

feat: add recipent webhook handler

---

src/Middle/Proxy/RecipientProxy.php

Adição da geração do kyc link ao RecipientProxy
Chamando o createKycLink do RecipientProxy

feat: added recipient link to RecipientProxy

---

src/Kernel/Abstractions/AbstractModuleCoreSetup.php
src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
src/Kernel/Aggregates/Order.php
src/Kernel/Repositories/ChargeRepository.php
src/Kernel/Repositories/ConfigurationRepository.php
src/Kernel/Repositories/OrderRepository.php
src/Kernel/Services/APIService.php
src/Kernel/Services/ChargeService.php
src/Kernel/Services/LogService.php
src/Kernel/Services/MoneyService.php
src/Kernel/Services/OrderService.php
src/Kernel/ValueObjects/Installment.php
src/Marketplace/Repositories/RecipientRepository.php
src/Payment/Aggregates/Customer.php
src/Payment/Aggregates/Order.php
src/Payment/Repositories/CustomerRepository.php
src/Payment/Repositories/SavedCardRepository.php
src/Recurrence/Repositories/ChargeRepository.php
src/Recurrence/Repositories/PlanRepository.php
src/Recurrence/Repositories/ProductSubscriptionRepository.php
src/Recurrence/Repositories/RepetitionRepository.php
src/Recurrence/Repositories/SubProductRepository.php
src/Recurrence/Repositories/SubscriptionItemRepository.php
src/Recurrence/Repositories/SubscriptionRepository.php
src/Webhook/Repositories/WebhookRepository.php

> [!IMPORTANT]
Updates realizados para Woocommerce e não mergeados para esse repositório.
Compras no Magento.

chore: update with woocommerce changes

---

src/Hub/Commands/InstallCommand.php

> [!IMPORTANT]
* Removido validação da instalação de integração do Hub

fix: removed integration validation

---

src/Kernel/I18N/PTBR.php
src/Kernel/Services/InstallmentService.php

> [!IMPORTANT]
* Removido exibição de porcentagem de juros nas parcelas de cartão de crédito

improv: removed interest percentage on card installments

---

composer.json
src/Payment/Aggregates/Address.php

> [!IMPORTANT]
Corrige a validação que estava ignorando valores "SN"
Compras com SN ou string no campo numero.

fix: validation address number and update sdk version
