src/Hub/Services/HubIntegrationService.php, src/Kernel/Abstractions/AbstractModuleCoreSetup.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-125
| **What?**         | Changes the base api url to hub's one if hub is enabled.
| **Why?**          | To allow hub integrations automatically when using core.
**Important Notes:**
- We're still using **staging hub url**. 
Add additional informations like screenshots, issue link, etc
* Add pull request labels.
* Check base branch.
* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
=> Adds hub url handling

src/Kernel/Factories/Configurations/PixConfigFactory.php, src/Kernel/ValueObjects/Configuration/PixConfig.php, src/Payment/Factories/PaymentFactory.php, tests/Kernel/Factories/Configurations/PixConfigFactoryTest.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-162
| **What?**         | Makes core uses pix additional information if it is set.
| **Why?**          | To show extra information when scanning pix qrcode.
| **How?**          | adding additional information in `PixConfig.php` and using additionalInformation, if is set in module's config.
=> Uses additional information in pix payments

src/Recurrence/Aggregates/Subscription.php, tests/Recurrence/Aggregates/SubscriptionTest.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-212
| **What?**         | Fixes error to create subscriptions for new buyers.
| **Why?**          | Our module is not sending the billing_address parameter inside the card object.
| **How?**          | Removing code snippet to send the card object.
=> Fixes error to create subscriptions

src/Hub/Commands/AbstractCommand.php, src/Hub/Services/HubIntegrationService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-228
| **What?**         | Adds logs when token not found in database.
| **Why?**          | To help us to identify the issue if we see this scenario in a case.
| **How?**          | Adding a log message when the instalToken is empty.
**Notes**
- Also fix a visibility issue in logService parameter of AbstractCommand.
=> Fixes logs when hub token not found in database

src/Payment/Aggregates/Customer.php, tests/Payment/Aggregates/CustomerTests.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-185
| **What?**         | Sanitize customer document to fix invalid request
| **Why?**          | Because the invalid request caused an error when editing a customer or update the credit to the customer's account
=> Sanitize customer document

azure-pipelines.yml
| **What?**         | Removes old php version from Azure CI
| **Why?**          | Because we don't support it anymore and this version is breaking the CI
=> Removes old php version from Azure CI

src/Kernel/Log/JsonPrettyFormatter.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-484
| **What?**         | Pagar.me Core does not support Magento 2.4.4.
| **Why?**          | Allow Magento works in latest version.
| **How?**          | Monolog library dependency can be any version.
=> Missing function's return type declaration

src/Kernel/Services/OrderService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-280
| **What?**         | Added a bypass to checkout with blank shipping information.
| **Why?**          | Could not finish checkout when shipping information was blank.
| **How?**          | Edited a `if` statement that already checked if shipping is `null`, to also check if it is blank.
=> Bug fix allowing checkout when shipping is empty

src/Kernel/ValueObjects/ChargeStatus.php, src/Kernel/ValueObjects/TransactionStatus.php, src/Recurrence/Aggregates/Charge.php, src/Recurrence/Aggregates/Subscription.php, src/Recurrence/ValueObjects/SubscriptionStatus.php, src/Webhook/Services/ChargeRecurrenceService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-283
| **What?**         | Apply canceled status to subscriptions when receiving chargeback
| **Why?**          | To handle the chargeback charge
| **How?**          | It implements the treatment where when you receive the charge.chargedback of the subscription, you cancel it.
=> :heavy_plus_sign: apply canceled status to subscriptions when receiving chargeback

src/Recurrence/Aggregates/Charge.php, src/Recurrence/Services/InvoiceService.php, src/Webhook/Services/ChargeRecurrenceService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-269
| **What?**         | Assigns chargedback status to invoices on recurrence
| **Why?**          | To assign the same status as dash
| **How?**          | When the webhook receives the charge.chagedback
=> :heavy_plus_sign: assigns chargeback status to invoices

src/Recurrence/Aggregates/Charge.php, src/Webhook/Services/ChargeRecurrenceService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-269
| **What?**         | Assigns chargedback status to invoices on recurrence
| **Why?**          | To assign the same status as dash
| **How?**          | When the webhook receives the charge.chagedback
=> PAOPN-269: assign failed status to invoice

src/Maintenance/Services/OrderInfoRetrieverService.php
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-301](https://mundipagg.atlassian.net/browse/PAOPN-301)
| **What?**         | Hiding customer info from API
| **Why?**          | To hide sensitive information
| **How?**          | Using `preg_replace()` function to replace parts of the information with asterisk characters
=> PAOPN-301 Hiding customer info from API

src/Kernel/Log/BlurData.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-288
| **What?**         | Fix bug caused by null parameter in holdername
| **Why?**          | Because PHP 8 does not accept null in string functions
| **How?**          | If null, it is replaced by an empty string
=> fix: holdername is null in logger

src/Payment/Factories/CustomerFactory.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-349
| **What?**         | Add telephone on customer update.
| **Why?**          | If the admin updated the customer's registration, the API was updated and removed the customer's phone, generating a problem in the generation of charges in the recurrence
| **How?**          | Add telephone on customer update.
=> PAOPN-349: add telephone on customer update

src/Kernel/ValueObjects/Id/RecipientId.php, src/Marketplace/Aggregates/Recipient.php, src/Marketplace/Aggregates/Split.php, src/Marketplace/Factories/RecipientFactory.php, src/Marketplace/Repositories/RecipientRepository.php, src/Marketplace/Services/RecipientService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-304
| **What?**         | Update mundipagg dependency to paymecoreapi. Update to accept both V5 recipient_id patterns
| **Why?**          | Mundipagg is discontinued and if the recipient_id is not updated, it makes it impossible for the user to create new recipients
| **How?**          |  Update mundipagg dependency to paymecoreapi. Update to accept both V5 recipient_id patterns
* In a Mark1 V5 update, it stopped adopting the rp_xxxxxxxxxxxxxxxx pattern and went back to using the re_xxxxxxxxxxxxxxxxxxxxxxxxx pattern
=> Release Split

src/Kernel/Abstractions/AbstractModuleCoreSetup.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-425
| **What?**         | Removing unnecessary configurations update in bootstrap.
| **Why?**          | Updating configurations in every bootstrap call without needing.
| **How?**          | Removing unnecessary configurations update in bootstrap.
=> PAOPN-425: Removing unnecessary configurations update in bootstrap

src/Marketplace/Services/RecipientService.php, src/Payment/Aggregates/Address.php, src/Payment/Factories/PaymentFactory.php, src/Recurrence/Services/CartRules/CurrentProduct.php, src/Recurrence/Services/PlanService.php, src/Webhook/Aggregates/Webhook.php, tests/Marketplace/Aggregates/SplitTest.php, tests/Recurrence/Aggregates/SubscriptionTest.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-393
| **What?**         | Compatibilization with magento 2.4.6 and PHP 8.2.
| **Why?**          | Work with more versions.
| **How?**          | Adding properties definition to compatibilize with PHP 8.2.
=> feat: compatibilization with magento 2.4.6 and PHP 8.2

src/Recurrence/Services/RepetitionService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-548
| **What?**         | Removing parentheses from cycle title builder.
| **Why?**          | Conflict with other magento product options that use parentheses.
| **How?**          | Removing parentheses from cycle title builder.
=> feat: removing parentheses from cycle title builder

src/Kernel/Log/BlurData.php, src/Kernel/Services/LogService.php
| **Issue**         | https://github.com/pagarme/magento2/issues/168
| **What?**         | Set the first argument  fom blurStringSensitiveData to optional, and updated Log service to not throw  an exception and stop the current order flow.
| **Why?**          | To not have inconsistencies between the platforms because the module failed to log for some reason.
| **How?**          | Setting the first argument  fom blurStringSensitiveData to optional, and updated Log service to not throw an exception and stop the current order flow.
#
* Add pull request labels.
* Check base branch.
* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting …
=> Fix log to files stoping the order flow

src/Kernel/Log/BlurData.php
| **What?**         | Defined default value to blurStringSensitiveData `$delimiter` parameter
| **Why?**          | To fix deprecated functionality
| **How?**          | Defining default value as `null`
=> fix: add default value to blurStringSensitiveData parameter

src/Kernel/Aggregates/Configuration.php, src/Payment/Aggregates/Payments/BoletoPayment.php, src/Payment/Factories/PaymentFactory.php, src/Payment/ValueObjects/BoletoBank.php, src/Recurrence/Services/ResponseHandlers/ErrorExceptionHandler.php, tests/Recurrence/Aggregates/ProductSubscriptionTest.php, tests/mock/Concrete/Migrate.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-608
| **What?**         | Adding due_at, bank and instructions information to be send to createOrder for billet payment method.
| **Why?**          | Send correct information to create billet order.
| **How?**          | Adding due_at, bank and instructions information to be send to createOrder for billet payment method.
=> fix: adding due_at, bank and instructions information to be send to createOrder for billet payment method

src/Kernel/Log/BlurData.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-660
| **What?**         | Cedilla substr generate specials unicode block.
| **Why?**          | Generated log for order request and response are written with null value.
| **How?**          | Change str functions to be mb_str
=> fix: cedilla substr generate specials unicode block

src/Kernel/Aggregates/Order.php
> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **stg**.
Adicionado método alternativo para buscar as informações de QrCode de Pix ou URL de Boleto. Ver tarefa: https://mundipagg.atlassian.net/browse/PAOPN-663
Defini `null` no `$orderId` para testar o retorno da nova função quando a original falhar. Retorno está conforme esperado. Testado pedidos com Pix, Boleto e Cartão de Crédito. Todos ok!
=> feat: alternate pix and billet info
